# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'createserverpage.ui'
##
## Created by: Qt User Interface Compiler version 6.6.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QGroupBox, QLabel,
    QLineEdit, QListWidget, QListWidgetItem, QPushButton,
    QSizePolicy, QWidget)
import rc_resource

class Ui_CreateServerPage(object):
    def setupUi(self, CreateServerPage):
        if not CreateServerPage.objectName():
            CreateServerPage.setObjectName(u"CreateServerPage")
        CreateServerPage.resize(700, 450)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Maximum, QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(CreateServerPage.sizePolicy().hasHeightForWidth())
        CreateServerPage.setSizePolicy(sizePolicy)
        palette = QPalette()
        brush = QBrush(QColor(255, 255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(48, 48, 48, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        brush2 = QBrush(QColor(72, 72, 72, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Light, brush2)
        brush3 = QBrush(QColor(60, 60, 60, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        brush4 = QBrush(QColor(24, 24, 24, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Dark, brush4)
        brush5 = QBrush(QColor(204, 204, 204, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        palette.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        brush6 = QBrush(QColor(0, 0, 0, 255))
        brush6.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush6)
        palette.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette.setBrush(QPalette.Active, QPalette.Shadow, brush6)
        palette.setBrush(QPalette.Active, QPalette.AlternateBase, brush4)
        brush7 = QBrush(QColor(255, 255, 220, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ToolTipBase, brush7)
        palette.setBrush(QPalette.Active, QPalette.ToolTipText, brush6)
        brush8 = QBrush(QColor(255, 255, 255, 127))
        brush8.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush8)
#endif
        palette.setBrush(QPalette.Active, QPalette.Accent, brush6)
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush6)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Shadow, brush6)
        palette.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush7)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush6)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush8)
#endif
        palette.setBrush(QPalette.Inactive, QPalette.Accent, brush6)
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Shadow, brush6)
        palette.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush7)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush6)
        brush9 = QBrush(QColor(24, 24, 24, 127))
        brush9.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush9)
#endif
        brush10 = QBrush(QColor(34, 34, 34, 255))
        brush10.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Accent, brush10)
        CreateServerPage.setPalette(palette)
        font = QFont()
        font.setFamilies([u"Noto Sans"])
        CreateServerPage.setFont(font)
        self.label = QLabel(CreateServerPage)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 20, 151, 16))
        font1 = QFont()
        font1.setFamilies([u"Noto Sans"])
        font1.setPointSize(12)
        font1.setBold(True)
        self.label.setFont(font1)
        self.nextBtn = QPushButton(CreateServerPage)
        self.nextBtn.setObjectName(u"nextBtn")
        self.nextBtn.setGeometry(QRect(600, 400, 80, 25))
        self.serverName = QLineEdit(CreateServerPage)
        self.serverName.setObjectName(u"serverName")
        self.serverName.setGeometry(QRect(20, 60, 161, 25))
        self.label_2 = QLabel(CreateServerPage)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 40, 54, 17))
        self.loaderChoice = QComboBox(CreateServerPage)
        icon = QIcon()
        icon.addFile(u":/imgs/icons/minecraft_logo.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.loaderChoice.addItem(icon, "")
        icon1 = QIcon()
        icon1.addFile(u":/imgs/icons/papermc-logomark.png", QSize(), QIcon.Normal, QIcon.Off)
        self.loaderChoice.addItem(icon1, "")
        icon2 = QIcon()
        icon2.addFile(u":/imgs/icons/purpur.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.loaderChoice.addItem(icon2, "")
        icon3 = QIcon()
        icon3.addFile(u":/imgs/icons/NeoForged.png", QSize(), QIcon.Normal, QIcon.Off)
        self.loaderChoice.addItem(icon3, "")
        icon4 = QIcon()
        icon4.addFile(u":/imgs/icons/velocity-blue.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.loaderChoice.addItem(icon4, "")
        icon5 = QIcon()
        icon5.addFile(u":/imgs/icons/cloud-network.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.loaderChoice.addItem(icon5, "")
        self.loaderChoice.addItem("")
        self.loaderChoice.addItem("")
        self.loaderChoice.setObjectName(u"loaderChoice")
        self.loaderChoice.setGeometry(QRect(190, 60, 161, 25))
        self.label_3 = QLabel(CreateServerPage)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(190, 40, 81, 21))
        self.serverFileGroupBox = QGroupBox(CreateServerPage)
        self.serverFileGroupBox.setObjectName(u"serverFileGroupBox")
        self.serverFileGroupBox.setGeometry(QRect(20, 90, 661, 301))
        self.label_4 = QLabel(self.serverFileGroupBox)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 30, 251, 17))
        self.jarFileLocation = QLineEdit(self.serverFileGroupBox)
        self.jarFileLocation.setObjectName(u"jarFileLocation")
        self.jarFileLocation.setGeometry(QRect(90, 50, 561, 25))
        self.browseFileBtn = QPushButton(self.serverFileGroupBox)
        self.browseFileBtn.setObjectName(u"browseFileBtn")
        self.browseFileBtn.setGeometry(QRect(10, 50, 71, 25))
        self.minecraftVersionList = QListWidget(self.serverFileGroupBox)
        self.minecraftVersionList.setObjectName(u"minecraftVersionList")
        self.minecraftVersionList.setGeometry(QRect(10, 100, 321, 191))
        self.label_5 = QLabel(self.serverFileGroupBox)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 80, 421, 17))
        self.buildList = QListWidget(self.serverFileGroupBox)
        self.buildList.setObjectName(u"buildList")
        self.buildList.setGeometry(QRect(330, 100, 321, 192))

        self.retranslateUi(CreateServerPage)

        QMetaObject.connectSlotsByName(CreateServerPage)
    # setupUi

    def retranslateUi(self, CreateServerPage):
        CreateServerPage.setWindowTitle(QCoreApplication.translate("CreateServerPage", u"Create new server", None))
        self.label.setText(QCoreApplication.translate("CreateServerPage", u"Create new server", None))
        self.nextBtn.setText(QCoreApplication.translate("CreateServerPage", u"Next", None))
        self.serverName.setPlaceholderText(QCoreApplication.translate("CreateServerPage", u"Enter your server name...", None))
        self.label_2.setText(QCoreApplication.translate("CreateServerPage", u"Name", None))
        self.loaderChoice.setItemText(0, QCoreApplication.translate("CreateServerPage", u"Vanilla", None))
        self.loaderChoice.setItemText(1, QCoreApplication.translate("CreateServerPage", u"Paper", None))
        self.loaderChoice.setItemText(2, QCoreApplication.translate("CreateServerPage", u"Purpur", None))
        self.loaderChoice.setItemText(3, QCoreApplication.translate("CreateServerPage", u"NeoForge", None))
        self.loaderChoice.setItemText(4, QCoreApplication.translate("CreateServerPage", u"Velocity", None))
        self.loaderChoice.setItemText(5, QCoreApplication.translate("CreateServerPage", u"BungeeCord", None))
        self.loaderChoice.setItemText(6, QCoreApplication.translate("CreateServerPage", u"Fabric", None))
        self.loaderChoice.setItemText(7, QCoreApplication.translate("CreateServerPage", u"Forge", None))

        self.label_3.setText(QCoreApplication.translate("CreateServerPage", u"Mod Loader", None))
        self.serverFileGroupBox.setTitle(QCoreApplication.translate("CreateServerPage", u"Server .jar File", None))
        self.label_4.setText(QCoreApplication.translate("CreateServerPage", u"Manually choose the downloaded server file", None))
        self.browseFileBtn.setText(QCoreApplication.translate("CreateServerPage", u"Browse...", None))
        self.label_5.setText(QCoreApplication.translate("CreateServerPage", u"Automatically download server file (Only available for some mod loaders)", None))
    # retranslateUi

