# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'manageserver.ui'
##
## Created by: Qt User Interface Compiler version 6.6.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QApplication, QCheckBox, QComboBox,
    QHeaderView, QLabel, QLineEdit, QPlainTextEdit,
    QPushButton, QSizePolicy, QSlider, QSpinBox,
    QTabWidget, QTableWidget, QTableWidgetItem, QTextEdit,
    QWidget)
import rc_resource

class Ui_ManageServer(object):
    def setupUi(self, ManageServer):
        if not ManageServer.objectName():
            ManageServer.setObjectName(u"ManageServer")
        ManageServer.resize(700, 450)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ManageServer.sizePolicy().hasHeightForWidth())
        ManageServer.setSizePolicy(sizePolicy)
        palette = QPalette()
        brush = QBrush(QColor(255, 255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(48, 48, 48, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        brush2 = QBrush(QColor(72, 72, 72, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Light, brush2)
        brush3 = QBrush(QColor(60, 60, 60, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        brush4 = QBrush(QColor(24, 24, 24, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Dark, brush4)
        brush5 = QBrush(QColor(204, 204, 204, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        palette.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        brush6 = QBrush(QColor(0, 0, 0, 255))
        brush6.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush6)
        palette.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette.setBrush(QPalette.Active, QPalette.Shadow, brush6)
        palette.setBrush(QPalette.Active, QPalette.AlternateBase, brush4)
        brush7 = QBrush(QColor(255, 255, 220, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ToolTipBase, brush7)
        palette.setBrush(QPalette.Active, QPalette.ToolTipText, brush6)
        brush8 = QBrush(QColor(255, 255, 255, 127))
        brush8.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush8)
#endif
        palette.setBrush(QPalette.Active, QPalette.Accent, brush6)
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush6)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Shadow, brush6)
        palette.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush7)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush6)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush8)
#endif
        palette.setBrush(QPalette.Inactive, QPalette.Accent, brush6)
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Shadow, brush6)
        palette.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush7)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush6)
        brush9 = QBrush(QColor(24, 24, 24, 127))
        brush9.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush9)
#endif
        brush10 = QBrush(QColor(34, 34, 34, 255))
        brush10.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Accent, brush10)
        ManageServer.setPalette(palette)
        font = QFont()
        font.setFamilies([u"Noto Sans"])
        ManageServer.setFont(font)
        self.modLoaderIcon = QLabel(ManageServer)
        self.modLoaderIcon.setObjectName(u"modLoaderIcon")
        self.modLoaderIcon.setGeometry(QRect(20, 20, 51, 51))
        self.modLoaderIcon.setPixmap(QPixmap(u":/imgs/icons/papermc-logomark.png"))
        self.modLoaderIcon.setScaledContents(True)
        self.serverLabel = QLabel(ManageServer)
        self.serverLabel.setObjectName(u"serverLabel")
        self.serverLabel.setGeometry(QRect(80, 25, 491, 21))
        font1 = QFont()
        font1.setFamilies([u"Noto Sans"])
        font1.setPointSize(12)
        font1.setBold(True)
        self.serverLabel.setFont(font1)
        self.tabWidget = QTabWidget(ManageServer)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(10, 80, 681, 361))
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.label = QLabel(self.tab)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 20, 81, 17))
        self.serverStateLabel = QLabel(self.tab)
        self.serverStateLabel.setObjectName(u"serverStateLabel")
        self.serverStateLabel.setGeometry(QRect(102, 18, 81, 21))
        self.serverStateLabel.setFont(font1)
        self.serverToggleBtn = QPushButton(self.tab)
        self.serverToggleBtn.setObjectName(u"serverToggleBtn")
        self.serverToggleBtn.setGeometry(QRect(580, 20, 81, 25))
        icon = QIcon()
        icon.addFile(u":/imgs/icons/power-switch.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.serverToggleBtn.setIcon(icon)
        self.serverToggleBtn.setIconSize(QSize(12, 12))
        self.serverToggleBtn.setCheckable(True)
        self.restartBtn = QPushButton(self.tab)
        self.restartBtn.setObjectName(u"restartBtn")
        self.restartBtn.setEnabled(False)
        self.restartBtn.setGeometry(QRect(580, 50, 81, 25))
        icon1 = QIcon()
        icon1.addFile(u":/imgs/icons/reload.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.restartBtn.setIcon(icon1)
        self.restartBtn.setIconSize(QSize(12, 12))
        self.openServerDirBtn = QPushButton(self.tab)
        self.openServerDirBtn.setObjectName(u"openServerDirBtn")
        self.openServerDirBtn.setGeometry(QRect(10, 290, 161, 25))
        icon2 = QIcon()
        icon2.addFile(u":/imgs/icons/folder.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.openServerDirBtn.setIcon(icon2)
        self.openServerDirBtn.setIconSize(QSize(12, 12))
        self.tabWidget.addTab(self.tab, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.backupList = QTableWidget(self.tab_4)
        if (self.backupList.columnCount() < 2):
            self.backupList.setColumnCount(2)
        __qtablewidgetitem = QTableWidgetItem()
        self.backupList.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.backupList.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        if (self.backupList.rowCount() < 1):
            self.backupList.setRowCount(1)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.backupList.setItem(0, 0, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        self.backupList.setItem(0, 1, __qtablewidgetitem3)
        self.backupList.setObjectName(u"backupList")
        self.backupList.setGeometry(QRect(10, 40, 658, 281))
        self.backupList.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.pushButton = QPushButton(self.tab_4)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(10, 10, 111, 25))
        icon3 = QIcon()
        icon3.addFile(u":/imgs/icons/plus.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton.setIcon(icon3)
        self.pushButton.setIconSize(QSize(12, 12))
        self.pushButton_2 = QPushButton(self.tab_4)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(130, 10, 121, 25))
        icon4 = QIcon()
        icon4.addFile(u":/imgs/icons/trash-can.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton_2.setIcon(icon4)
        self.pushButton_2.setIconSize(QSize(12, 12))
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.javaExecLabel = QLabel(self.tab_2)
        self.javaExecLabel.setObjectName(u"javaExecLabel")
        self.javaExecLabel.setGeometry(QRect(10, 10, 121, 17))
        font2 = QFont()
        font2.setFamilies([u"Noto Sans"])
        font2.setBold(True)
        self.javaExecLabel.setFont(font2)
        self.javaExecInput = QLineEdit(self.tab_2)
        self.javaExecInput.setObjectName(u"javaExecInput")
        self.javaExecInput.setGeometry(QRect(100, 30, 221, 25))
        self.javaExecBrowseBtn = QPushButton(self.tab_2)
        self.javaExecBrowseBtn.setObjectName(u"javaExecBrowseBtn")
        self.javaExecBrowseBtn.setGeometry(QRect(10, 30, 80, 25))
        self.onlineMode = QCheckBox(self.tab_2)
        self.onlineMode.setObjectName(u"onlineMode")
        self.onlineMode.setGeometry(QRect(10, 60, 121, 23))
        self.onlineMode.setFont(font2)
        self.initialHeapSizeSlider = QSlider(self.tab_2)
        self.initialHeapSizeSlider.setObjectName(u"initialHeapSizeSlider")
        self.initialHeapSizeSlider.setGeometry(QRect(370, 35, 211, 16))
        self.initialHeapSizeSlider.setMinimum(2048)
        self.initialHeapSizeSlider.setMaximum(16384)
        self.initialHeapSizeSlider.setSingleStep(512)
        self.initialHeapSizeSlider.setPageStep(1024)
        self.initialHeapSizeSlider.setValue(4096)
        self.initialHeapSizeSlider.setOrientation(Qt.Horizontal)
        self.initialHeapSizeLabel = QLabel(self.tab_2)
        self.initialHeapSizeLabel.setObjectName(u"initialHeapSizeLabel")
        self.initialHeapSizeLabel.setGeometry(QRect(340, 10, 161, 17))
        self.initialHeapSizeLabel.setFont(font2)
        self.minInitialHeapSizeLabel = QLabel(self.tab_2)
        self.minInitialHeapSizeLabel.setObjectName(u"minInitialHeapSizeLabel")
        self.minInitialHeapSizeLabel.setGeometry(QRect(340, 34, 31, 17))
        self.maxInitialHeapSizeLabel = QLabel(self.tab_2)
        self.maxInitialHeapSizeLabel.setObjectName(u"maxInitialHeapSizeLabel")
        self.maxInitialHeapSizeLabel.setGeometry(QRect(590, 34, 31, 17))
        self.minMaxHeapSizeLabel = QLabel(self.tab_2)
        self.minMaxHeapSizeLabel.setObjectName(u"minMaxHeapSizeLabel")
        self.minMaxHeapSizeLabel.setGeometry(QRect(340, 79, 31, 17))
        self.maxHeapSizeLabel = QLabel(self.tab_2)
        self.maxHeapSizeLabel.setObjectName(u"maxHeapSizeLabel")
        self.maxHeapSizeLabel.setGeometry(QRect(340, 55, 161, 17))
        self.maxHeapSizeLabel.setFont(font2)
        self.maxMaxHeapSizeLabel = QLabel(self.tab_2)
        self.maxMaxHeapSizeLabel.setObjectName(u"maxMaxHeapSizeLabel")
        self.maxMaxHeapSizeLabel.setGeometry(QRect(590, 79, 31, 17))
        self.maxHeapSizeSlider = QSlider(self.tab_2)
        self.maxHeapSizeSlider.setObjectName(u"maxHeapSizeSlider")
        self.maxHeapSizeSlider.setGeometry(QRect(370, 80, 211, 16))
        self.maxHeapSizeSlider.setMinimum(2048)
        self.maxHeapSizeSlider.setMaximum(16384)
        self.maxHeapSizeSlider.setSingleStep(512)
        self.maxHeapSizeSlider.setValue(4096)
        self.maxHeapSizeSlider.setOrientation(Qt.Horizontal)
        self.initialHeapValueLabel = QLabel(self.tab_2)
        self.initialHeapValueLabel.setObjectName(u"initialHeapValueLabel")
        self.initialHeapValueLabel.setGeometry(QRect(630, 34, 41, 17))
        self.maxHeapValueLabel = QLabel(self.tab_2)
        self.maxHeapValueLabel.setObjectName(u"maxHeapValueLabel")
        self.maxHeapValueLabel.setGeometry(QRect(630, 79, 41, 17))
        self.label_2 = QLabel(self.tab_2)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 90, 91, 21))
        self.label_2.setFont(font2)
        self.maxPlayerInput = QSpinBox(self.tab_2)
        self.maxPlayerInput.setObjectName(u"maxPlayerInput")
        self.maxPlayerInput.setGeometry(QRect(10, 110, 49, 29))
        self.maxPlayerInput.setMinimum(1)
        self.maxPlayerInput.setMaximum(1000)
        self.maxPlayerInput.setValue(20)
        self.label_3 = QLabel(self.tab_2)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 145, 151, 17))
        self.label_3.setFont(font2)
        self.argsEdit = QPlainTextEdit(self.tab_2)
        self.argsEdit.setObjectName(u"argsEdit")
        self.argsEdit.setGeometry(QRect(10, 170, 311, 151))
        self.argsPresets = QComboBox(self.tab_2)
        self.argsPresets.addItem("")
        self.argsPresets.addItem("")
        self.argsPresets.addItem("")
        self.argsPresets.addItem("")
        self.argsPresets.addItem("")
        self.argsPresets.addItem("")
        self.argsPresets.setObjectName(u"argsPresets")
        self.argsPresets.setGeometry(QRect(171, 140, 151, 25))
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_5 = QWidget()
        self.tab_5.setObjectName(u"tab_5")
        self.tableWidget = QTableWidget(self.tab_5)
        if (self.tableWidget.columnCount() < 3):
            self.tableWidget.setColumnCount(3)
        __qtablewidgetitem4 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, __qtablewidgetitem4)
        __qtablewidgetitem5 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, __qtablewidgetitem5)
        __qtablewidgetitem6 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, __qtablewidgetitem6)
        if (self.tableWidget.rowCount() < 1):
            self.tableWidget.setRowCount(1)
        self.tableWidget.setObjectName(u"tableWidget")
        self.tableWidget.setGeometry(QRect(10, 10, 660, 311))
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.serverLog = QTextEdit(self.tab_3)
        self.serverLog.setObjectName(u"serverLog")
        self.serverLog.setGeometry(QRect(10, 10, 657, 281))
        self.serverLog.setReadOnly(True)
        self.serverCommandInput = QLineEdit(self.tab_3)
        self.serverCommandInput.setObjectName(u"serverCommandInput")
        self.serverCommandInput.setGeometry(QRect(10, 290, 657, 25))
        self.tabWidget.addTab(self.tab_3, "")
        self.serverInfoLabel = QLabel(ManageServer)
        self.serverInfoLabel.setObjectName(u"serverInfoLabel")
        self.serverInfoLabel.setGeometry(QRect(80, 45, 491, 16))

        self.retranslateUi(ManageServer)

        self.tabWidget.setCurrentIndex(3)


        QMetaObject.connectSlotsByName(ManageServer)
    # setupUi

    def retranslateUi(self, ManageServer):
        ManageServer.setWindowTitle(QCoreApplication.translate("ManageServer", u"Form", None))
        self.modLoaderIcon.setText("")
        self.serverLabel.setText(QCoreApplication.translate("ManageServer", u"Server name", None))
        self.label.setText(QCoreApplication.translate("ManageServer", u"Your server is", None))
        self.serverStateLabel.setText(QCoreApplication.translate("ManageServer", u"OFFLINE", None))
        self.serverToggleBtn.setText(QCoreApplication.translate("ManageServer", u" Start", None))
        self.restartBtn.setText(QCoreApplication.translate("ManageServer", u" Restart", None))
        self.openServerDirBtn.setText(QCoreApplication.translate("ManageServer", u"Open Server Directory", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("ManageServer", u"Summary", None))
        ___qtablewidgetitem = self.backupList.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("ManageServer", u"Name", None));
        ___qtablewidgetitem1 = self.backupList.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("ManageServer", u"Time of creation", None));

        __sortingEnabled = self.backupList.isSortingEnabled()
        self.backupList.setSortingEnabled(False)
        self.backupList.setSortingEnabled(__sortingEnabled)

        self.pushButton.setText(QCoreApplication.translate("ManageServer", u"New Backup", None))
        self.pushButton_2.setText(QCoreApplication.translate("ManageServer", u"Delete Selected", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QCoreApplication.translate("ManageServer", u"Backups", None))
        self.javaExecLabel.setText(QCoreApplication.translate("ManageServer", u"Java Executable", None))
        self.javaExecInput.setPlaceholderText(QCoreApplication.translate("ManageServer", u"Leave blank to use default", None))
        self.javaExecBrowseBtn.setText(QCoreApplication.translate("ManageServer", u"Browse...", None))
        self.onlineMode.setText(QCoreApplication.translate("ManageServer", u"Online Mode", None))
        self.initialHeapSizeLabel.setText(QCoreApplication.translate("ManageServer", u"Initial Memory Usage", None))
        self.minInitialHeapSizeLabel.setText(QCoreApplication.translate("ManageServer", u"2GB", None))
        self.maxInitialHeapSizeLabel.setText(QCoreApplication.translate("ManageServer", u"16GB", None))
        self.minMaxHeapSizeLabel.setText(QCoreApplication.translate("ManageServer", u"2GB", None))
        self.maxHeapSizeLabel.setText(QCoreApplication.translate("ManageServer", u"Max Memory Usage", None))
        self.maxMaxHeapSizeLabel.setText(QCoreApplication.translate("ManageServer", u"16GB", None))
        self.initialHeapValueLabel.setText(QCoreApplication.translate("ManageServer", u"(4GB)", None))
        self.maxHeapValueLabel.setText(QCoreApplication.translate("ManageServer", u"(4GB)", None))
        self.label_2.setText(QCoreApplication.translate("ManageServer", u"Max Players", None))
        self.label_3.setText(QCoreApplication.translate("ManageServer", u"Custom JVM Arguments", None))
        self.argsPresets.setItemText(0, QCoreApplication.translate("ManageServer", u"None", None))
        self.argsPresets.setItemText(1, QCoreApplication.translate("ManageServer", u"Aikar's Flags", None))
        self.argsPresets.setItemText(2, QCoreApplication.translate("ManageServer", u"Aikar's Flags (12GB+)", None))
        self.argsPresets.setItemText(3, QCoreApplication.translate("ManageServer", u"Shenandoah GC", None))
        self.argsPresets.setItemText(4, QCoreApplication.translate("ManageServer", u"ZGC", None))
        self.argsPresets.setItemText(5, QCoreApplication.translate("ManageServer", u"Custom", None))

#if QT_CONFIG(tooltip)
        self.argsPresets.setToolTip(QCoreApplication.translate("ManageServer", u"JVM Arguments Presets", None))
#endif // QT_CONFIG(tooltip)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("ManageServer", u"Configuration", None))
        ___qtablewidgetitem2 = self.tableWidget.horizontalHeaderItem(0)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("ManageServer", u"Enabled", None));
        ___qtablewidgetitem3 = self.tableWidget.horizontalHeaderItem(1)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("ManageServer", u"Name", None));
        ___qtablewidgetitem4 = self.tableWidget.horizontalHeaderItem(2)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("ManageServer", u"Version", None));
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QCoreApplication.translate("ManageServer", u"Mods/Plugins", None))
        self.serverCommandInput.setPlaceholderText(QCoreApplication.translate("ManageServer", u"Enter command...", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("ManageServer", u"Console", None))
        self.serverInfoLabel.setText(QCoreApplication.translate("ManageServer", u"Paper 1.20.4 Build 960", None))
    # retranslateUi

